# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 919f9c2157b0d93432c8f195cd259e83545d81cb4576c4bdfa0cfb4a1f4aff244e49cd561ed9ead0ffd1c67847db286689af82538f23efceaf4ad81800458b57

test:
  secret_key_base: 86853208d71442e88dc3337599f71d31e0b0eed3dee6b2e1421b5a6880fa0d4b7b081e45ef13db91332d7354ac15be3a0df18df7ee4609e773e9da7ec760f27a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
